#!/usr/bin/env bash
# Type-checks every Kotlin file in the app with the real Kotlin compiler.
#
# The Android SDK, Compose and the other libraries cannot be downloaded in every
# environment, so tools/stubs holds hand-written stand-ins with the same shapes.
# That is enough for the compiler to resolve types and catch what a static scan
# cannot: a method absent from a return type, a stale field after a refactor, a
# missing import.
#
# Not a substitute for the Gradle build: annotation processing (Hilt, Room) and
# resource linking happen only there.
#
# Needs kotlinc: set KOTLINC, or place it at /tmp/kotlinc.
set -e
cd "$(dirname "$0")/.."
KOTLINC="${KOTLINC:-/tmp/kotlinc/bin/kotlinc}"
if [ ! -x "$KOTLINC" ]; then
  echo "  kotlinc not found — skipping type-check (set KOTLINC=/path/to/bin/kotlinc)"
  exit 0
fi
COROUTINES="$(dirname "$KOTLINC")/../lib/kotlinx-coroutines-core-jvm.jar"
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

echo "Building API stubs..."
"$KOTLINC" tools/stubs/android/*.kt -cp "$COROUTINES" -nowarn -d "$OUT/android" 2>/dev/null
"$KOTLINC" tools/stubs/compose/*.kt -cp "$COROUTINES:$OUT/android" -nowarn -d "$OUT/compose" 2>/dev/null
"$KOTLINC" tools/stubs/generated/*.kt -nowarn -d "$OUT/generated" 2>/dev/null

echo "Type-checking every source file..."
"$KOTLINC" app/src/main/java/com/middleeastcontainer \
  -cp "$OUT/android:$OUT/compose:$OUT/generated:$COROUTINES" \
  -nowarn -d "$OUT/classes" 2>"$OUT/errors.txt" || true

# A crashed compiler prints an exception and no "error:" lines at all. Counting
# errors alone would report that as success — which it silently did once.
if grep -qE "^exception:|internal error|Please report this problem" "$OUT/errors.txt"; then
  echo "  *** the compiler crashed — this is NOT a pass"
  head -3 "$OUT/errors.txt"
  exit 1
fi

# Generated by the kotlinx.serialization compiler plugin on @Serializable
# classes. The plugin needs its runtime, which is not obtainable here, so this
# one call cannot be resolved. Listed explicitly rather than filtered loosely,
# so nothing else can hide behind it.
# Unit tests are compiled by the same CI job that builds the APK, so a fake that
# no longer implements its interface fails the whole run — after the APK has
# already been produced. That reached CI once because every checker scanned main
# sources only.
if [ -d app/src/test ]; then
  echo "Type-checking test sources..."
  "$KOTLINC" tools/stubs/test/*.kt -cp "$COROUTINES" -nowarn -d "$OUT/junit" 2>/dev/null
  # Every test source except the one needing MockWebServer, which is a whole
  # HTTP server and not worth stubbing. Named explicitly rather than filtered by
  # message, so nothing else can hide behind the exemption.
  TEST_SOURCES=$(find app/src/test -name '*.kt' ! -name 'MecrcApiWireCompatibilityTest.kt')
  "$KOTLINC" $TEST_SOURCES app/src/main/java/com/middleeastcontainer \
    -cp "$OUT/android:$OUT/compose:$OUT/generated:$OUT/junit:$COROUTINES" \
    -nowarn -d "$OUT/testclasses" 2>>"$OUT/errors.txt" || true
fi

KNOWN_GENERATED="unresolved reference 'serializer'"

REAL=$(grep "error:" "$OUT/errors.txt" | grep -v "$KNOWN_GENERATED" || true)
SKIPPED=$(grep -c "$KNOWN_GENERATED" "$OUT/errors.txt" || true)

if [ -n "$REAL" ]; then
  echo "$REAL" | sed 's|.*middleeastcontainer/||'
  echo "  $(echo "$REAL" | wc -l) error(s)"
  exit 1
fi
echo "  [PASS] every Kotlin file type-checks"
[ "$SKIPPED" -gt 0 ] && echo "  ($SKIPPED plugin-generated serializer() call not checkable here)"
exit 0
